task_name: TreeHeightUnet_NEW
tags:
- dev
train: true
test: true
ckpt_path: null
seed: null
train_data:
  _target_: src.data.MTaskSemSegDataset.TreeHeightDataset
  images_dir: ${oc.env:TREEHEIGHT_IMAGES,${paths.root_dir}/data/TreeHeight/image_256}
  mask_dir: ${oc.env:TREEHEIGHT_MASKS,${paths.root_dir}/data/TreeHeight/treecover_256}
  assist_dir: ${oc.env:TREEHEIGHT_HEIGHTS,${paths.root_dir}/data/TreeHeight/nDSM_256}
  scale: 1
  mask_values: [0, 1]
  batch_size: 16
inference_data:
  _target_: src.data.Inference_RSTiledPredDataset.RSTiledPredDatasetLD
  file_path: ${oc.env:TREEHEIGHT_RASTER,${paths.root_dir}/data/TreeHeight/raster_1m_cropped.tif}
  patch_size: 256
  overlap: 0.25
  batch_size: 8
  num_workers: 4
model:
  _target_: src.models.MheadUnet.MHeadUnet.MheadUNetLM
  net:
    _target_: src.models.MheadUnet.MHeadUnet.MheadUNet
    n_channels: 5
    n_classes: 1
    bilinear: false
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.0003
    weight_decay: 0.00001
    _partial_: true
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: min
    factor: 0.5
    patience: 5
    verbose: true
    _partial_: true
  compile: false
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/checkpoints
    filename: epoch_{epoch:03d}
    monitor: val/total_loss
    verbose: false
    save_last: true
    save_top_k: 1
    mode: min
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: null
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val/total_loss
    min_delta: 0.0
    patience: 100
    verbose: false
    mode: min
    strict: true
    check_finite: true
    stopping_threshold: null
    divergence_threshold: null
    check_on_train_epoch_end: null
  inference_callback:
    _target_: src.callbacks.Inference_RSTiledPredCallback.PredictionCallback
    output_path: ${paths.output_dir}/prediction_results.tif
    overlap: ${inference_data.overlap}
    task_names: ["height", "cover"]
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: -1
  rich_progress_bar:
    _target_: lightning.pytorch.callbacks.RichProgressBar
logger:
  wandb:
    _target_: swanlab.integration.pytorch_lightning.SwanLabLogger
    project: ${task_name}
    name: ${now:%Y-%m-%d_%H-%M-%S}_unet_lr${model.optimizer.lr}_bs${train_data.batch_size}
    save_dir: ${paths.log_dir}
    mode: local
    # log_model: false
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 10
  max_epochs: 80
  accelerator: gpu
  precision: 16-mixed
  devices: 1
  check_val_every_n_epoch: 1
  deterministic: false
paths:
  root_dir: ${oc.env:PROJECT_ROOT,.}
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: true
  enforce_tags: true
  print_config: true
