task_name: TreeHeightUnet
tags:
- dev
train: true
test: true
ckpt_path: null
seed: null
data:
  train_data:
    _target_: src.data.MTaskSemSegDataset.TreeHeightDataset
    images_dir: ${oc.env:TREEHEIGHT_IMAGES,${paths.root_dir}/data/TreeHeight/images}
    mask_dir: ${oc.env:TREEHEIGHT_MASKS,${paths.root_dir}/data/TreeHeight/masks}
    assist_dir: ${oc.env:TREEHEIGHT_HEIGHTS,${paths.root_dir}/data/TreeHeight/heights}
    scale: 1
    mask_values: [0, 101]
    batch_size: 8
  inference_data:
    _target_: src.data.Inference_RSTiledPredDataset.RSTiledPredDatasetLD
    file_path: ${oc.env:TREEHEIGHT_RASTER,${paths.root_dir}/data/TreeHeight/raster.tif}
    patch_size: 256
    overlap: 0.25
    batch_size: 8
    num_workers: 4
model:
  _target_: src.models.ClassificationTask.SwinMLP.SwinClassifier
  num_classes: 5
  backbone:
    _target_: src.models.backbones.SwinTransformer
    structure_type: swin_tiny_patch4_window7_224
    out_indices: [3]
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.00003
    weight_decay: 0.0
callbacks:
  model_checkpoint:  # 内置的回调函数，用于保存模型
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/checkpoints
    filename: epoch_{epoch:03d}
    monitor: val_f1+val_r2
    verbose: false
    save_last: true
    save_top_k: 1
    mode: max
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: null
  early_stopping:    # 内置的回调函数，用于提前停止训练
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_f1+val_r2
    min_delta: 0.0
    patience: 100
    verbose: false
    mode: max
    strict: true
    check_finite: true
    stopping_threshold: null
    divergence_threshold: null
    check_on_train_epoch_end: null
  inference_callback:
    _target_: src.callbacks.Inference_RSTiledPredCallback.PredictionCallback
    output_path: ${paths.output_dir}/prediction_results.tif
    overlap: ${data.inference_data.overlap}   # 与数据集的overlap对应, ${} 用于引用其他配置, 便于修改
    task_names: ["height", "cover"]  # 与模型的多头输出对应
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: -1
  rich_progress_bar:
    _target_: lightning.pytorch.callbacks.RichProgressBar
logger:
  wandb:
    _target_: lightning.pytorch.loggers.WandbLogger
    project: "tree_height_unet"
    # 设置name和学习率以及一些其他的参数
    name: lr:${model.optimizer.lr}_batch:${data.train_data.batch_size}
    save_dir: ${paths.log_dir}
    log_model: false
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 10
  max_epochs: 50
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 1
  deterministic: false
paths:
  root_dir: ${oc.env:PROJECT_ROOT,.}
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: true
  enforce_tags: true
  print_config: true
